services:
  broker-rabbitmq:
    image: rabbitmq:3.13.3-management-alpine
    container_name: broker-rabbitmq
    ports:
      - "5672:5672"      # AMQP port
      - "15672:15672"    # Management interface port
    volumes:
      - type: bind
        source: ./config/rabbitmq.conf
        target: /etc/rabbitmq/rabbitmq.conf
      - type: bind
        source: ./config/definitions.json
        target: /etc/rabbitmq/definitions.json
  
  database-postgres:
    image: postgres:14.9-alpine3.18
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
    container_name: database-postgres
    environment:
      POSTGRES_DB: "rent-vehicles"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - database-postgres-volume:/var/lib/postgresql/data
  
  database-mongo:
    image: mongo:5.0.27
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
    container_name: database-mongo
    ports:
      - "27017:27017"
    volumes:
      - database-mongo-volume:/data/db
      - ./config/init.js:/docker-entrypoint-initdb.d/init.js:ro

networks:
  default:
    driver: bridge
    name: rent-vehicles-sln

volumes:
  database-postgres-volume:
    name: database-postgres-volume
  
  database-mongo-volume:
    name: database-mongo-volume