// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rent.Vehicles.Entities.Contexts;

#nullable disable

namespace Rent.Vehicles.Entities.Migrations
{
    [DbContext(typeof(RentVehiclesContext))]
    [Migration("20240624173240_CreateRentalPlanes")]
    partial class CreateRentalPlanes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rent.Vehicles.Entities.Command", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer")
                        .HasColumnName("action_type");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("smallint[]")
                        .HasColumnName("data");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("SagaId")
                        .HasColumnType("uuid")
                        .HasColumnName("saga_id");

                    b.Property<int>("SerializerType")
                        .HasColumnType("integer")
                        .HasColumnName("serializer_type");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_commands");

                    b.HasAlternateKey("SagaId")
                        .HasName("ak_commands_saga_id");

                    b.ToTable("commands", "events");
                });

            modelBuilder.Entity("Rent.Vehicles.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("smallint[]")
                        .HasColumnName("data");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("SagaId")
                        .HasColumnType("uuid")
                        .HasColumnName("saga_id");

                    b.Property<int>("SerializerType")
                        .HasColumnType("integer")
                        .HasColumnName("serializer_type");

                    b.Property<int>("StatusType")
                        .HasColumnType("integer")
                        .HasColumnName("status_type");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("SagaId")
                        .HasDatabaseName("ix_events_saga_id");

                    b.ToTable("events", "events");
                });

            modelBuilder.Entity("Rent.Vehicles.Entities.RentalPlane", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("cost");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<int>("NumberOfDays")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_days");

                    b.Property<decimal>("PostEndDateFine")
                        .HasColumnType("numeric")
                        .HasColumnName("post_end_date_fine");

                    b.Property<decimal>("PreEndDatePercentageFine")
                        .HasColumnType("numeric")
                        .HasColumnName("pre_end_date_percentage_fine");

                    b.HasKey("Id")
                        .HasName("pk_rental_planes");

                    b.ToTable("rentalPlanes", "vehicles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("282ff9de-7436-4875-82da-2ca1b894f08f"),
                            Cost = 30.0m,
                            Created = new DateTime(2024, 6, 24, 17, 32, 39, 755, DateTimeKind.Utc).AddTicks(708),
                            NumberOfDays = 7,
                            PostEndDateFine = 50.0m,
                            PreEndDatePercentageFine = 1.20m
                        },
                        new
                        {
                            Id = new Guid("68b5779a-27f9-4e35-949c-d66f1915701b"),
                            Cost = 28.0m,
                            Created = new DateTime(2024, 6, 24, 17, 32, 39, 755, DateTimeKind.Utc).AddTicks(778),
                            NumberOfDays = 15,
                            PostEndDateFine = 50.0m,
                            PreEndDatePercentageFine = 1.40m
                        },
                        new
                        {
                            Id = new Guid("b96cac96-d3cb-40ae-a8de-0c67f08400ae"),
                            Cost = 22.0m,
                            Created = new DateTime(2024, 6, 24, 17, 32, 39, 755, DateTimeKind.Utc).AddTicks(790),
                            NumberOfDays = 30,
                            PostEndDateFine = 50.0m,
                            PreEndDatePercentageFine = 1.0m
                        },
                        new
                        {
                            Id = new Guid("b664a818-09a2-4ac0-b58b-820624f6adb0"),
                            Cost = 20.0m,
                            Created = new DateTime(2024, 6, 24, 17, 32, 39, 755, DateTimeKind.Utc).AddTicks(801),
                            NumberOfDays = 45,
                            PostEndDateFine = 50.0m,
                            PreEndDatePercentageFine = 1.0m
                        },
                        new
                        {
                            Id = new Guid("2860ce87-765a-4df7-9c9b-00fb02d49265"),
                            Cost = 18.0m,
                            Created = new DateTime(2024, 6, 24, 17, 32, 39, 755, DateTimeKind.Utc).AddTicks(811),
                            NumberOfDays = 50,
                            PostEndDateFine = 50.0m,
                            PreEndDatePercentageFine = 1.0m
                        });
                });

            modelBuilder.Entity("Rent.Vehicles.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("birthday");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("license_number");

                    b.Property<string>("LicensePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("license_path");

                    b.Property<int>("LicenseType")
                        .HasColumnType("integer")
                        .HasColumnName("license_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", "vehicles");
                });

            modelBuilder.Entity("Rent.Vehicles.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("license_plate");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.ToTable("vehicles", "vehicles");
                });

            modelBuilder.Entity("Rent.Vehicles.Entities.Event", b =>
                {
                    b.HasOne("Rent.Vehicles.Entities.Command", null)
                        .WithMany()
                        .HasForeignKey("SagaId")
                        .HasPrincipalKey("SagaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_events_commands_saga_id");
                });
#pragma warning restore 612, 618
        }
    }
}
