// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rent.Vehicles.Entities.Contexts;

#nullable disable

namespace Rent.Vehicles.Entities.Migrations
{
    [DbContext(typeof(RentVehiclesContext))]
    [Migration("20240624175017_CreateRents")]
    partial class CreateRents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rent.Vehicles.Entities.Command", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer")
                        .HasColumnName("action_type");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("smallint[]")
                        .HasColumnName("data");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("SagaId")
                        .HasColumnType("uuid")
                        .HasColumnName("saga_id");

                    b.Property<int>("SerializerType")
                        .HasColumnType("integer")
                        .HasColumnName("serializer_type");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_commands");

                    b.HasAlternateKey("SagaId")
                        .HasName("ak_commands_saga_id");

                    b.ToTable("commands", "events");
                });

            modelBuilder.Entity("Rent.Vehicles.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("smallint[]")
                        .HasColumnName("data");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("SagaId")
                        .HasColumnType("uuid")
                        .HasColumnName("saga_id");

                    b.Property<int>("SerializerType")
                        .HasColumnType("integer")
                        .HasColumnName("serializer_type");

                    b.Property<int>("StatusType")
                        .HasColumnType("integer")
                        .HasColumnName("status_type");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("SagaId")
                        .HasDatabaseName("ix_events_saga_id");

                    b.ToTable("events", "events");
                });

            modelBuilder.Entity("Rent.Vehicles.Entities.Rent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("cost");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<decimal>("DailyCost")
                        .HasColumnType("numeric")
                        .HasColumnName("daily_cost");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<DateTime>("EstimatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("estimated_date");

                    b.Property<int>("NumberOfDays")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_days");

                    b.Property<decimal>("PostEndDateFine")
                        .HasColumnType("numeric")
                        .HasColumnName("post_end_date_fine");

                    b.Property<decimal>("PreEndDatePercentageFine")
                        .HasColumnType("numeric")
                        .HasColumnName("pre_end_date_percentage_fine");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_rents");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_rents_user_id");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_rents_vehicle_id");

                    b.ToTable("rents", "vehicles");
                });

            modelBuilder.Entity("Rent.Vehicles.Entities.RentalPlane", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<decimal>("DailyCost")
                        .HasColumnType("numeric")
                        .HasColumnName("daily_cost");

                    b.Property<int>("NumberOfDays")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_days");

                    b.Property<decimal>("PostEndDateFine")
                        .HasColumnType("numeric")
                        .HasColumnName("post_end_date_fine");

                    b.Property<decimal>("PreEndDatePercentageFine")
                        .HasColumnType("numeric")
                        .HasColumnName("pre_end_date_percentage_fine");

                    b.HasKey("Id")
                        .HasName("pk_rental_planes");

                    b.ToTable("rentalPlanes", "vehicles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("39e02a68-9b2f-4638-869d-2a1b51145a9b"),
                            Created = new DateTime(2024, 6, 24, 17, 50, 17, 247, DateTimeKind.Utc).AddTicks(3373),
                            DailyCost = 30.0m,
                            NumberOfDays = 7,
                            PostEndDateFine = 50.0m,
                            PreEndDatePercentageFine = 1.20m
                        },
                        new
                        {
                            Id = new Guid("45df35af-ab37-4fa2-8324-f03806ddd48d"),
                            Created = new DateTime(2024, 6, 24, 17, 50, 17, 247, DateTimeKind.Utc).AddTicks(3426),
                            DailyCost = 28.0m,
                            NumberOfDays = 15,
                            PostEndDateFine = 50.0m,
                            PreEndDatePercentageFine = 1.40m
                        },
                        new
                        {
                            Id = new Guid("a8118564-6c17-4e76-be3c-c8947fda30ad"),
                            Created = new DateTime(2024, 6, 24, 17, 50, 17, 247, DateTimeKind.Utc).AddTicks(3436),
                            DailyCost = 22.0m,
                            NumberOfDays = 30,
                            PostEndDateFine = 50.0m,
                            PreEndDatePercentageFine = 1.0m
                        },
                        new
                        {
                            Id = new Guid("d8a5a35f-c718-435b-a119-1ea2d679acb6"),
                            Created = new DateTime(2024, 6, 24, 17, 50, 17, 247, DateTimeKind.Utc).AddTicks(3444),
                            DailyCost = 20.0m,
                            NumberOfDays = 45,
                            PostEndDateFine = 50.0m,
                            PreEndDatePercentageFine = 1.0m
                        },
                        new
                        {
                            Id = new Guid("699b68db-2f0f-41ed-a414-b7fca8dcb5e1"),
                            Created = new DateTime(2024, 6, 24, 17, 50, 17, 247, DateTimeKind.Utc).AddTicks(3452),
                            DailyCost = 18.0m,
                            NumberOfDays = 50,
                            PostEndDateFine = 50.0m,
                            PreEndDatePercentageFine = 1.0m
                        });
                });

            modelBuilder.Entity("Rent.Vehicles.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("birthday");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("license_number");

                    b.Property<string>("LicensePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("license_path");

                    b.Property<int>("LicenseType")
                        .HasColumnType("integer")
                        .HasColumnName("license_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", "vehicles");
                });

            modelBuilder.Entity("Rent.Vehicles.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("license_plate");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.ToTable("vehicles", "vehicles");
                });

            modelBuilder.Entity("Rent.Vehicles.Entities.Event", b =>
                {
                    b.HasOne("Rent.Vehicles.Entities.Command", null)
                        .WithMany()
                        .HasForeignKey("SagaId")
                        .HasPrincipalKey("SagaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_events_commands_saga_id");
                });

            modelBuilder.Entity("Rent.Vehicles.Entities.Rent", b =>
                {
                    b.HasOne("Rent.Vehicles.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rents_users_user_id");

                    b.HasOne("Rent.Vehicles.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rents_vehicles_vehicle_id");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
